tasks:
  - storages:
      - ftp_server
    database: local_db
    archive:
      driver: tar
      password: "${COMPRESS_PASSWORD}"
storages:
  - name: ftp_server
    host: "${FTP_HOST}"
    port: "${FTP_PORT}"
    user: "${FTP_USER}"
    password: "${FTP_PASSWORD}"
    path: "/public_html/backups/"
    driver: ftp
databases:
  - name: local_db
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    database: "${DB_DATABASE}"
    driver: mysql
